### ISSUE TITLE
Code Highlighting in markdown

### ISSUE THREAD

**Issue by countcain** [slideshow-s9/slideshow#14]
I wrote the code below in my markdown file:

<% coderay :lang=>'ruby', :line_numbers=>:inline do%>
 puts 'Hello'
<% end %>

After I built it.It didn't work in a right way.
Coderay create a div block and a <pre 'code'> block within it.
But markdown renders  the <pre 'code'> block as a part of a code paragraph.
So the final html result is:
<div class="CodeRay"> "<pre 'code'>".....</div>
It is wrong.
Please figure it out. Thanks.

**Comment by geraldb** [comment]
FYI: The coderay highlighter is no longer supported in the core. If want to use it  you're welcome to create a plugin. Cheers.
