### ISSUE TITLE
crashes on windows

### ISSUE THREAD

**Issue by brianray** [slideshow-s9/slideshow#15]
just installed from gem...

C:\Users\brray\Documents\GitHub\chipy_nlp\docs>slideshow build slides
fetcher 0.4.2 on Ruby 1.9.3 (2013-11-22) [i386-mingw32]
Slide Show (S9) 2.3.0 on Ruby 1.9.3 (2013-11-22) [i386-mingw32]
**\* depreciated API call [Pakman::Finder.initialize] - do NOT pass in logger; no longer required/needed; logger arg will get removed
Preparing slideshow 'slides'...
  Patching !-directives (0 slide/style-directives)...
  Preparing %-directives (0 slide/style directives, 0 class/clear expr-directives, 0/0 block-directives)...
  Removing %-comments (0 lines, 0 begin/end-blocks, 0 end-blocks)...
  Reading 0 headers: ...
  Patching embedded Ruby (erb) code Django-style (0 {{-expressions, 0/0 {%-statements)...
  Patching embedded Ruby (erb) code for aliases (0 include/class-aliases)...
  Running embedded Ruby (erb) code/helpers...
  Patching {{{/}}}-code blocks (0/0 blocks, 0/0 escaped blocks)...

**\* error: undefined method `rest_to_html' for #Slideshow::Gen:0x292f4d0

The RST file is the one from the install docs.

**Comment by geraldb** [comment]
FYI: The ReST format is no longer supported. Will get moved to a plugin (so others if interested can keep it up).

**Comment by geraldb** [comment]
Again thanks for reporting. ReST is no longer supported in the core. You're welcome to create a plugin (if want to use it). Cheers.
