### ISSUE TITLE
Building impress.js hit an invalid byte sequence.

### ISSUE THREAD

**Issue by raesene** [slideshow-s9/slideshow#2]
At the moment the build command seems to be hitting an error where binary files (e.g. png files) are hit in the template.

For examples

create a new sample with impress.js.
```
slideshow new -t impress.js
```
then try to build the sample

```
slideshow build -t impress.js impress.js.text
```
generates an error

```
Merging to impress.js.css...
  Loading page (from file) >/home/rorym/.slideshow/templates/impress.js/js/impress.js<...
  Copying to js/impress.js from /home/rorym/.slideshow/templates/impress.js/js/impress.js...
  Loading page (from file) >/home/rorym/.slideshow/templates/impress.js/apple-touch-icon.png<...

*** error: invalid byte sequence in UTF-8
```

running with verbose indicates that this line is where the problem is hit

```
*** error: invalid byte sequence in UTF-8

/home/rorym/.rvm/gems/ruby-2.2.1/gems/pakman-0.6.0/lib/pakman/page.rb:41:in `match': invalid byte sequence in UTF-8 (ArgumentError)
```

**Comment by geraldb** [comment]
Thanks for trying slideshow with impress.js.  Thanks for reporting. Will try to fix it later this week. Thanks for your patience. Have a great week. Cheers.

**Comment by geraldb** [comment]
@raesene Sorry for the long wait - not sure if you're still interested. I will push out a new version in the next days (Tuesday/Wednesday) with a fix for the encoding. In the meantime would be great if you could help and try if this (work around) works e.g. using (the switch -Ku) "forces" UTF-8 encoding for everything):

    $ ruby -Ku -S slideshow build -t impress.js impress.js.text

Thanks for trying and thanks for the patience. Cheers.

**Comment by geraldb** [comment]
@raesene FYI: If you're still interested I pushed a new pakman gem (handles the merging of templates) and it's now working - to update try:

    $ gem install pakman

New version is 0.7.0 (old version was 0.6.0) and than retry as usual (it should now finally work as advertised) e.g.:

     $ slideshow build -t impress.js impress.js.text
  
 Thanks for trying. Cheers.
