### ISSUE TITLE
rst generation is not compatible with pandoc 1.8.1.1

### ISSUE THREAD

**Issue by Edgy** [slideshow-s9/slideshow#9]
It appears that pandoc (atleast version 1.8.1.1) does not generate div_h1 tags, instead it generates only h1 tags.  So the gsub! in lib/slideshow/filters/slide_filter.rb will fail, which means that contents are never put into the resulting html.  The quick solution I came up with was editing slide_filter.rb and adding:

 51   puts "  Adding #{slide_count} slide breaks (using div_h1 rule)..."
 52
 53+   add_slide_directive_before_h1 content
 54
 55   content

**Comment by geraldb** [comment]
Thanks for reporting. Will try to get the pandoc (markdown) converter code reworked in a future update. Most of the markdown code moved to its own gem, that is, [markdown](http://geraldb.github.com/markdown) to make it easier to keep up with and configure markdown engines such as pandoc. Cheers.

**Comment by geraldb** [comment]
@Edgy Not sure if you're still interested. With version 3 rst is no longer supported in the core. You're welcome to create a plugin.Cheers.
